language: node_js
node_js: "8"

os:
  - linux
  - osx

python:
  - "2.7"

cache: yarn

install:
  - yarn

script:
  - yarn coverage
  - yarn coverage-report
  - npm install codecov -g
  - codecov
  - yarn build