language: node_js
node_js: "8"

os:
  - linux
  - osx

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python2.7

cache: yarn

install:
  - yarn

script:
  - yarn coverage
  - yarn coverage-report
  - npm install codecov -g
  - codecov
  - yarn build