language: node_js
node_js:
  - "8"

os:
  - linux
  - osx

cache: yarn

install:
  - yarn

stages:
  - test
  - build

jobs:
  include:
    - stage: test
    script: yarn test

    -stage: build
    script: yarn build